project:
  type: website
  output-dir: docs
  

website:
  title: "ğ™…ğ™’ ğ™ğ™ğ˜¼ğ™„"
  page-footer:
    center: Â© 2024- ğ™…ğ™’ ğ™ğ™ğ˜¼ğ™„. All rights reserved.
  navbar:
    right:
      - text: About
        href: index.qmd
      - text: Notes
        href: notes.qmd
      - icon: github
        href: https://github.com/jiewenTsai

  search: 
    location: navbar
    type: overlay

    
format:
  html:
    theme: 
      dark: darkly
      light: flatly
      
    css: styles.css
    code-fold: true
    toc: true
    citation: true
    csl: theapa7.csl
    
    
comments:
  utterances:
    repo: jiewenTsai/jiewenTsai.github.io
editor: visual

